name: fasum
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.4.4

dependencies:
  flutter:
    sdk: flutter
  firebase_data_connect: ^0.1.3+2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.6
  path: ^1.9.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  flutter_image_compress: ^2.4.0
  geolocator: ^13.0.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
